### ISSUE TITLE
block level todo master snippet do not work

### ISSUE THREAD

**Issue by L0cutus** [pengx17/logseq-plugin-todo-master#10]
Watch the video or i'm missing something?
![Peek 26-01-2022 09-40](https://user-images.githubusercontent.com/90012/151130614-e9ecbaf1-8d4b-4dcc-a311-18a826f0ca66.gif)

(Logseq 0.59 + 1.5.1)

Thanks !

**Comment by pengx17** [comment]
There are some issues introduced in 1.5.*. I have reverted the changes and publish 1.6.0

**Comment by L0cutus** [comment]
> There are some issues introduced in 1.5.*. I have reverted the changes and publish 1.6.0

Just installed, same problem ;-)

**Comment by pengx17** [comment]
Ops .. I forget to push my local changes

**Comment by L0cutus** [comment]
Solved Thanks!
(another question, why in your demo video the bar is composed by more than one color while the mine by only one?)
Thanks again!

**Comment by pengx17** [comment]
There are 2 colors:  🔵 for NOW/DOING and 🟢 for DONE.

**Comment by L0cutus** [comment]
> There are 2 colors: large_blue_circle for NOW/DOING and green_circle for DONE.

Ha ok! I thought that the colors change depended on how many tasks were done
