### ISSUE TITLE
Sometimes it 'Lost' reference?

### ISSUE THREAD

**Issue by L0cutus** [pengx17/logseq-plugin-todo-master#11]
seems that sometimes it lost the reference to block
![Schermata del 2022-02-02 11-13-46](https://user-images.githubusercontent.com/90012/152134855-9fb3d5c6-2718-42b2-9fa7-b41d11433a2b.png)
k

**Comment by pengx17** [comment]
This is a duplicate. See https://github.com/pengx17/logseq-plugin-todo-master/issues/9
