### ISSUE TITLE
Request - ignore TODO in master block

### ISSUE THREAD

**Issue by JurijOrlow** [pengx17/logseq-plugin-todo-master#12]
Basically creating list with "TODO" prefix looks nice, but when using TODO Master with TODO in parent block, it is considered part of progress bar. Example:

- TODO Parent || Progress bar ||
    - DONE element 1
    - DONE element 2
    - DONE element 3

The progress bar will show 75% - 3 elements are marked as done, but parent is not. Can the progress bar ignore TODO in parent?

**Comment by pengx17** [comment]
Good point! I agree we should ignore the root block
________________________________
发件人: JurijOrlow ***@***.***>
发送时间: Thursday, February 3, 2022 9:31:54 PM
收件人: pengx17/logseq-plugin-todo-master ***@***.***>
抄送: Subscribed ***@***.***>
主题: [pengx17/logseq-plugin-todo-master] Request - ignore TODO in master block (Issue #12)


Basically creating list with "TODO" prefix looks nice, but when using TODO Master with TODO in parent block, it is considered part of progress bar. Example:

  *   TODO Parent || Progress bar ||
     *   DONE element 1
     *   DONE element 2
     *   DONE element 3

The progress bar will show 75% - 3 elements are marked as done, but parent is not. Can the progress bar ignore TODO in parent?

―

**Comment by chenxin0397** [comment]
为什么这个插件动不动就出现显示问题？每次都需要删掉旧的代码重新加入新的，感觉好复杂

**Comment by pengx17** [comment]
@chenxin0397 please do not comment unrelated issues.

**Comment by JurijOrlow** [comment]
Great! Please get onto it as fast as possible, thank you very much!

**Comment by pengx17** [comment]
fixed in https://github.com/pengx17/logseq-plugin-todo-master/releases/tag/v1.7.0
