### ISSUE TITLE
Not an issue, just thanks!

### ISSUE THREAD

**Issue by wzulfikar** [pengx17/logseq-plugin-todo-master#14]
I wasn't so sure what to use of this plugin when i saw it in marketplace. But once I started to plan things that should be done in any day within the week, I feel good! It's very helpful because I can track tasks across weeks. Thanks again ♥️

<img width=400 src=https://user-images.githubusercontent.com/7823011/155254817-897bba21-d202-482a-afb0-463a03b9d05e.png />

**Comment by redstreet** [comment]
Same here. Very useful in managing larger projects in a hierarchy. Thank you for writing and sharing this plugin!
