### ISSUE TITLE
could support to create progress bar in block property?

### ISSUE THREAD

**Issue by XinLi0111** [pengx17/logseq-plugin-todo-master#17]
Thanks for your plugin, I use it every day, and I find a inconvenient behavior of this plugin.

 I want to create a progress bar in block property, then I could use the query table function to collect the major task's progress, I don't want to create a page for these tasks, because even they have many sub-tasks, they are not a specific concept or object.

It will looks great when the tasks and progress showed in table view, but since the Logseq not support show the checkbox in table view, the question could be solved after logseq add the feature.

**Comment by pengx17** [comment]
Hi @XinLi0111 . todomaster plugin support requires an upstream fix in https://github.com/logseq/logseq/pull/4715 and should have been in the new nightly release.
E.g., the following will be supported:
![image](https://user-images.githubusercontent.com/584378/160519105-45f8dc1b-0a74-4553-80d6-e4b944a4243a.png)


BTW I am not sure if it can be rendered in tables view though ...

**Comment by XinLi0111** [comment]
Thanks for your great work. 👍
