### ISSUE TITLE
css position in breadcrumb

### ISSUE THREAD

**Issue by XinLi0111** [pengx17/logseq-plugin-todo-master#18]
![image](https://user-images.githubusercontent.com/31495943/162350386-99957840-acca-4e7a-821e-5a8683e42c63.png)
it seems that the width of progress bar in breadcrumb is smaller than expected.

**Comment by 3attaE** [comment]
Can we expand width directly? from 4ch -> 11ch.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/31028998/175757268-7d30f22c-1cab-4c4a-87e3-ebbe4a6cf629.png">

after that

<img width="680" alt="image" src="https://user-images.githubusercontent.com/31028998/175757246-d1c6892a-e9bf-43b7-a4bd-0a743f8233c3.png">

but more space in the breadcrumb when no mouse hovers it.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/31028998/175757253-bd257059-3f30-487a-9a9a-d89c41299128.png">

**Comment by XinLi0111** [comment]
Thanks. it's ok for me.

**Comment by pengx17** [comment]
Thanks for your suggestions. I think I would like to use a smarter way to do it, so that the width is using the actual element width, instead of using hard coded number.

**Comment by 3attaE** [comment]
I think you are totally right.
