### ISSUE TITLE
Support for queries

### ISSUE THREAD

**Issue by pgpais** [pengx17/logseq-plugin-todo-master#19]
Hello, I just started using this plugin and I was wondering if it is possible for it to work with queries?

What I do is everyday I query for all TODOs in the last 7 days or so. I am also experimenting with querying TODOs for a specific page.
The problem is that the progress bar does not seem to detect the TODOs in the query block.
![image](https://user-images.githubusercontent.com/19236561/163814369-0f3432c9-4df8-42b7-a1bc-a1442ea9ee51.png)

I might be doing something wrong but, if not, is it possible to support this use case?

**Comment by pengx17** [comment]
I think it is possible. Will add your request into my todo list.

**Comment by pgpais** [comment]
Wonderful, thank you very much!

**Comment by pengx17** [comment]
I think this may be easier to integrate into custom query titles, so that with todo-master plugin, Logseq could render the progress bar in today's journal page with the journal queries.

**Comment by pengx17** [comment]
Done, please check the latest version:
https://twitter.com/pengx17/status/1517550251497844736
