### ISSUE TITLE
Could this progress bar as a page property?

### ISSUE THREAD

**Issue by Amos369** [pengx17/logseq-plugin-todo-master#2]
Awesome work! 
what I want is the progress bar or the percentage of the progress showed in the page property.
so I can view it in a page query table . 😀

**Comment by pengx17** [comment]
@Amos369 the idea is pretty cool. I think page property can only contain user input texts and but it may not be very easy to think about a generic way to define a UI to sync the percentage value into a page/block property.
I think maybe the new `costum.js` feature added in Logseq 0.4.5 may be a solution. I will think about it as an alternative solution to replace the todo-master plugin.

**Comment by pengx17** [comment]
@Amos369 the plugin is now available in the marketplace and can be placed into page properties. Though I am not sure if it can be rendered correctly in query tables

**Comment by Amos369** [comment]
👍👍👍It's great, I love it. Thank you very much.
