### ISSUE TITLE
When there is more than one progress bar on the page, it cannot be displayed properly.

### ISSUE THREAD

**Issue by mafmadmaf** [pengx17/logseq-plugin-todo-master#20]
Thank you so much for the great plugin! I use it everyday.

After I upgraded Logseq (0.6.7) yesterday, the TODO Master (v1.9.4) had the following issue. 
Everything worked fine before.

- Scenario 1: I will use TODO Master on the daily Journal page. Now when I scroll down the Journal page, only one of the bars is displayed for the entire page (instead of one bar per daily journal).
- Scenario 2: I use TODO Master in different blocks (with sub-items) in a project, and now only one of the bars is displayed, and the bar will incorrectly display the progress of other parent bolcks.
- Scenario 3: The TODO Master progress bar displayed in Linked References has the same problem.

I've tried refreshing, re-indexing, and reinstalling the plugin multiple times, and the issue persists.

I love TODO Master! Thank you.

https://user-images.githubusercontent.com/13570154/166177559-1d6e0e89-e9b8-4f61-9392-dbf3de454e58.mov

m

**Comment by pengx17** [comment]
@mafmadmaf thanks! this issue should have been fixed

**Comment by mafmadmaf** [comment]
@pengx17 Thank you so much! They are all back. TODO Master helps me a lot! :)
