### ISSUE TITLE
Support for block references?

### ISSUE THREAD

**Issue by s-kyy** [pengx17/logseq-plugin-todo-master#21]
Hi, thanks for the wonderful plugin!

I was wondering if it can also support tasks that come from block references / block embeds. What I like to do is to note tasks in my daily notes and then reference them in a project note, but the way the todo-master plugin works now doesn't allow for that. 

Many thanks!

**Comment by pengx17** [comment]
I am not exactly sure what you are trying to achieve.
Do you think to render a progress over a custom query could help (which is just supported in recent versions)?

**Comment by s-kyy** [comment]
> I am not exactly sure what you are trying to achieve.

Let's say I have a main project note. I make tasks that I want to do throughout the day in my daily note but tag it with the project name. Yes, querying would capture them all, but I also want to be able to reorganize them into major subtasks for the project which is hard to do with a simple query. 

What I would like to do is to have block embed or block reference tasks from the daily notes to my main project note which is more organized. In each major subtask, I would be able to see the progress of all the indented tasks + referenced tasks from my other daily pages that I inserted manually. 

An alternative application are for those want to have a progress bar on their daily notes, but not all their tasks are from the same day. 

One of the reasons why I don't want to move blocks directly is due to the buggy nature of logseq when it comes to moving blocks. If I want to move a block to a new page it often creates a new block-id, resulting in a bunch of broken references. So to avoid that with tasks as well I want to be able to just block reference them instead of moving them to the project page. 

> Do you think to render a progress over a custom query could help (which is just supported in recent versions)?

If you don't find it worthwhile that's ok too. I'll make do with just from querying. 

Thanks for considering it!

**Comment by pengx17** [comment]
@s-kyy thanks for the explanation! I will take a look if it is feasible to get content from embedded blocks as well. 👍

**Comment by 3attaE** [comment]
@s-kyy, I added this feature in the 1.10.0 version. Update and try it out.

**Comment by 3attaE** [comment]
Thank you for your feedback. I didn't realize you use embed references.  

A PR has been submitted to fix this.  It will release when @pengx17 reviews.

> Gives 0 blocks:
> 
> `- <todo-master> {{embed ((...))}}`
> Gives 0 blocks:
>
> `- <todo-master> ((...))`

The above way is not supported yet
