### ISSUE TITLE
Show Progress of Priority Group

### ISSUE THREAD

**Issue by xZinio** [pengx17/logseq-plugin-todo-master#27]
I would like to use {{renderer :todomaster}} to display the progress of a certain priority group e.g. for all ToDo's tagges with Priority #C. Is this already possible or would this be considered a feature request? If it is already possible I would be interested in knowing how.

**Comment by pengx17** [comment]
I think this is doable. The trick is to put the todomaster macro with a query (either simple or advanced should both work). See this example:
```
{{renderer :todomaster}}
{{query (and (task now later todo) (priority B))}}
```
It will show all unfinished tasks with priority B:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/584378/188044175-4b898b6d-0d0f-4d86-ba5e-b0cbd9cfd1d3.png">

**Comment by xZinio** [comment]
Ok, then I'll probably try to figure out how queries work first and then come back to this solution as I am still pretty new to Logseq. Thanks for your help!

**Comment by xZinio** [comment]
Ok, so I've had a look at queries but still haven't figured out how to get this one to work. While trying though, I thought that this is actually kind of a dumb idea: Every time I add a new Task the overall number of tasks that ToDo-Master will consider increases. And the longer and longer I use it, the smaller the percentage (that is left to 100%) shown in ToDo-Master will get when I keep adding new ToDo's.
