### ISSUE TITLE
插件在块可用，在页面不可用

### ISSUE THREAD

**Issue by gsgqgyq** [pengx17/logseq-plugin-todo-master#3]
你好，感谢你的插件
在 1.3.3 版中，插件在块是可用的，但是在选择页面索引无反应

![](https://s2.loli.net/2021/12/04/KowlaUJ6NDitIyY.gif)

**Comment by pengx17** [comment]
🤔 似乎是标题文字出现汉字时会出问题，我研究研究

**Comment by pengx17** [comment]
Should have been fixed by https://github.com/pengx17/logseq-plugin-todo-master/releases/tag/v1.4.1
