### ISSUE TITLE
关于TODO进度条使用范围的问题

### ISSUE THREAD

**Issue by bwnjnOEI** [pengx17/logseq-plugin-todo-master#4]
搜索`TODO`页面后，进度条如何关联`Linked References`里的`TODO`? 或者有什么比较好的方式能实现全局的`TODO`的进度条？

![](https://s2.loli.net/2021/12/10/uECS4gjsz3cPBAD.png)

**Comment by pengx17** [comment]
你说的两种关联方式目前都不能支持。目前支持的只有：
- 收集当前页面的TODO状态
- 收集当前块及其子嗣的TODO状态
