### ISSUE TITLE
[Question] How to use it with text expander

### ISSUE THREAD

**Issue by ivanddm** [pengx17/logseq-plugin-todo-master#7]
Hi,

Thanks a lot for this plugin (and the awesome Dev theme as well). I was wondering if there is a way to insert the progress bar command (e.g., [TODO Master] Add Progress Bar for current page) in a logseq template or in some text snippet application such as text expander, so when using the text snippet the progress bar is added automatically.

Thanks in advance!

**Comment by pengx17** [comment]
@ivanddm thanks for using this plugin & Logseq!
Template support is currently limited to block level. E.g., put `{{renderer :todomaster}}` into the template, but I have not add page-level support yet.

**Comment by ivanddm** [comment]
That's excellent @pengx17. Block-level is kind of more than enough for me right now. Thanks again and keep up the excellent work 👍🏻
