### ISSUE TITLE
Unable to create a template with "Add progress bar to children blocks"

### ISSUE THREAD

**Issue by rodtrevizan** [pengx17/logseq-plugin-todo-master#8]
Hello,

I'm having trouble creating templates that self reference when used. 

Whenever I USE a template in a journal page, the progress bar doesn't update as it is still referencing the original template block.

Is there any "Dynamic Variables" config for this? Thanks for the help!

**Comment by pengx17** [comment]
Please see this comment:
https://github.com/pengx17/logseq-plugin-todo-master/issues/7#issuecomment-1005719449
