### ISSUE TITLE
Tracking target not found

### ISSUE THREAD

**Issue by MohamSayed** [pengx17/logseq-plugin-todo-master#9]
Every time  I refresh or relaunch the app progress bar stops working and displays this message:
  **Tracking target not found**

**Comment by pengx17** [comment]
The refactored solution in https://github.com/pengx17/logseq-plugin-todo-master/releases/tag/v1.5.0 did not work - I have reverted the change.

**Comment by kuoe0** [comment]
Got the same issue!

**Comment by wzulfikar** [comment]
Had the same issue when I renamed a page. The workaround is simple – just regenerate the snippet.

https://user-images.githubusercontent.com/7823011/155254696-678b2831-bd00-46ad-8cae-e0ac17cf84c6.mp4

**Comment by pengx17** [comment]
Please note that after 1.7.0, block-level progress bar will no longer require to have the hash part in `{{renderer :todomaster}}`.  You may need to remove them manually.
